version: 0.0.{build}
image: Visual Studio 2017
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: "{version}"
  package_version: "{version}"
before_build:
  - dotnet restore
build:
  verbosity: normal
  # publish_nuget: true